apiVersion: getambassador.io/v3alpha1
kind: Module
metadata:
  name: ambassador
  namespace: ingress
spec:
  config:
    diagnostics:
      enabled: true
    load_balancer:
      policy: round_robin
    use_remote_address: true
    enable_grpc_web: true
