---
# Customized values for ambassador helm chart 6.6.0

# TODO: add
#podDisruptionBudget: {}

namespace:
  name: ingress

# Additional container environment variable
# Uncomment or add additional environment variables for the container here.
env:
  # Exposing statistics via StatsD
  STATSD_ENABLED: true
  STATSD_HOST: localhost

image:
  repository: docker.io/datawire/aes
  tag: 1.14.2
  pullPolicy: IfNotPresent

service:
  type: LoadBalancer

  # Note that target http ports need to match your ambassador configurations service_port
  # https://www.getambassador.io/reference/modules/#the-ambassador-module
  ports:
    - name: http
      port: 80
    - name: https
      port: 443
  annotations:
    getambassador.io/config: |
      ---
      apiVersion: ambassador/v1
      kind: TLSContext
      name: tls-${PROVIDER}
      hosts: ['*.${COMMON_NAME}', ${COMMON_NAME}]
      secret: ambassador-certs-${PROVIDER}
      redirect_cleartext_from: 8080
      alpn_protocols: h2[, http/1.1]
      min_tls_version: v1.2
      max_tls_version: v1.3
      ---
      apiVersion: ambassador/v1
      kind: TLSContext
      name: tls-clouddns-sso
      hosts: ['*.alpha.docai.beer', 'alpha.docai.beer']
      secret: ambassador-certs-clouddns-sso
      redirect_cleartext_from: 8080
      alpn_protocols: h2[, http/1.1]
      min_tls_version: v1.2
      max_tls_version: v1.3
      ---
      apiVersion: ambassador/v1
      kind: Module
      name: ambassador
      config:
        diagnostics:
          enabled: true
        load_balancer:
          policy: round_robin
        use_remote_address: true

adminService:
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/path: "/metrics"
    prometheus.io/port: "8877"
  create: true
  type: ClusterIP
  port: 8877
  snapshotPort: 8005

podLabels:
  service: statsd-sink

################################################################################
## Ambassador Edge Stack Configuration                                        ##
################################################################################

# The Ambassador Edge Stack is free for limited use without a license key.
# Go to https://{ambassador-host}/edge_stack/admin/#dashboard to register
# for a community license key.

enableAES: false

# Ambassador ships with a basic redis instance. Configure the deployment with the options below.
redis:
  create: false