{{- $namespace := .Release.namespace }}
{{- range .Values.tls_contexts }}
{{- $common_name_normalized := .common_name | replace "!" "-" }}
{{- $common_name_domain := .common_name | replace "!" "." }}
{{- $provider = .provider }}
---
apiVersion: getambassador.io/v3alpha1
kind: Host
metadata:
  name: wildcard-{{- $common_name_normalized }}
  namespace: {{ $namespace }}
spec:
  requestPolicy:
    insecure:
      action: Redirect
  hostname: "*.{{- $common_name_domain }}"
  tlsSecret:
    name: "ambassador-certs-{{- $provider }}-{{- $common_name_normalized }}"
  tlsContext:
    name: tls-{{- $common_name_normalized }}
---
apiVersion: getambassador.io/v3alpha1
kind: Host
metadata:
  name: host-{{- $common_name_normalized }}
  namespace: {{ $namespace }}
spec:
  requestPolicy:
    insecure:
      action: Redirect
  hostname: "{{- $common_name_domain }}"
  tlsSecret:
    name: "ambassador-certs-{{- $provider }}-{{- $common_name_normalized }}"
  tlsContext:
    name: tls-{{- $common_name_normalized }}
{{- end }}
