{{- $namespace := .Release.namespace }}
{{- range $k, $v := .Values.tls_contexts }}
{{- $common_name := $k | replace "-" "." }}
---
apiVersion: getambassador.io/v3alpha1
kind: TLSContext
metadata:
  name: tls-{{- $common_name }}
  namespace: {{ $namespace }}
spec:
  hosts:
    - "*.{{- $k }}"
    - "{{- $k }}"
  secret: "ambassador-certs-{{- $v }}-{{- $common_name }}"
  redirect_cleartext_from: 8080
  alpn_protocols: h2[, http/1.1]
  min_tls_version: v1.2
  max_tls_version: v1.3
{{- end }}
