apiVersion: cert-manager.io/v1alpha2
kind: Issuer
metadata:
  name: letsencrypt-cloudflare
  namespace: ingress
spec:
  acme:
    email: infra-eng@doc.ai
    server: https://acme-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      name: letsencrypt-cloudflare-secret
    solvers:
     - dns01:
        cloudflare:
          email: owner@doc.ai
          apiKeySecretRef:
            name: helm-secrets-keys
            key: cloudflare-api-key